"""add color column to Order_item

Revision ID: 0c242085eb41
Revises: 8727ff8ac1a8
Create Date: 2022-05-20 14:18:08.424050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c242085eb41'
down_revision = '8727ff8ac1a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_item', sa.Column('color', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_item', 'color')
    # ### end Alembic commands ###
