"""create Item model and routes for achieving items

Revision ID: 25ab4066a500
Revises: 6295d2ffb5f0
Create Date: 2022-04-24 12:29:39.304683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25ab4066a500'
down_revision = '6295d2ffb5f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=64), nullable=True),
    sa.Column('item_category', sa.String(length=32), nullable=True),
    sa.Column('item_subtype', sa.String(length=16), nullable=True),
    sa.Column('item_image_link', sa.String(length=140), nullable=True),
    sa.Column('item_description', sa.String(length=140), nullable=True),
    sa.Column('item_price', sa.Float(precision=16), nullable=True),
    sa.Column('discount', sa.Integer(), nullable=True),
    sa.Column('num_of_item', sa.Integer(), nullable=True),
    sa.Column('item_sizes', sa.String(length=64), nullable=True),
    sa.Column('unavailable_sizes', sa.String(length=64), nullable=True),
    sa.Column('is_hot', sa.Boolean(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_item_name'), 'item', ['item_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_item_name'), table_name='item')
    op.drop_table('item')
    # ### end Alembic commands ###
