"""customer authentication

Revision ID: 359473b48841
Revises: a50144c4ee92
Create Date: 2022-05-11 01:43:04.927840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '359473b48841'
down_revision = 'a50144c4ee92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('customer_name', sa.String(length=64), nullable=True))
    op.add_column('customer', sa.Column('avatar', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'avatar')
    op.drop_column('customer', 'customer_name')
    # ### end Alembic commands ###
