"""add favorite_list field to Customer model

Revision ID: 4627732acd9d
Revises: b5eb5304dbc1
Create Date: 2022-05-10 23:39:40.297140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4627732acd9d'
down_revision = 'b5eb5304dbc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('favorite_list', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'favorite_list')
    # ### end Alembic commands ###
