"""delete message field in Contact_form

Revision ID: 54704d21a3ce
Revises: 7529a82a4338
Create Date: 2022-05-23 01:20:16.981081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54704d21a3ce'
down_revision = '7529a82a4338'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact_form', 'message')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_form', sa.Column('message', sa.VARCHAR(length=140), nullable=True))
    # ### end Alembic commands ###
