"""delete full_name and email_field in Contact_form model

Revision ID: 584dd551a258
Revises: 3dd627d1c973
Create Date: 2022-05-23 23:38:08.018029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '584dd551a258'
down_revision = '3dd627d1c973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact_form', 'email')
    op.drop_column('contact_form', 'full_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_form', sa.Column('full_name', sa.VARCHAR(length=32), nullable=True))
    op.add_column('contact_form', sa.Column('email', sa.VARCHAR(length=32), nullable=True))
    # ### end Alembic commands ###
