"""add full_name and email_field in Contact_form model

Revision ID: 639ff25f67e9
Revises: 584dd551a258
Create Date: 2022-05-23 23:40:25.419406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '639ff25f67e9'
down_revision = '584dd551a258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_form', sa.Column('full_name', sa.String(length=140), nullable=True))
    op.add_column('contact_form', sa.Column('email', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact_form', 'email')
    op.drop_column('contact_form', 'full_name')
    # ### end Alembic commands ###
