"""remove some fields related to item sizes and num of items, add new fields for new size logic

Revision ID: 8727ff8ac1a8
Revises: 359473b48841
Create Date: 2022-05-16 00:38:39.575615

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '8727ff8ac1a8'
down_revision = '359473b48841'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('M_stock', sa.Integer(), nullable=True))
    op.add_column('item', sa.Column('L_stock', sa.Integer(), nullable=True))
    op.add_column('item', sa.Column('XL_stock', sa.Integer(), nullable=True))
    op.add_column('item', sa.Column('XXL_stock', sa.Integer(), nullable=True))
    op.drop_column('item', 'num_of_item')
    op.drop_column('item', 'item_sizes')
    op.drop_column('item', 'unavailable_sizes')
    op.add_column('order_item', sa.Column('item_size', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_item', 'item_size')
    op.add_column('item', sa.Column('unavailable_sizes', sqlite.JSON(), nullable=True))
    op.add_column('item', sa.Column('item_sizes', sqlite.JSON(), nullable=True))
    op.add_column('item', sa.Column('num_of_item', sa.INTEGER(), nullable=True))
    op.drop_column('item', 'XXL_stock')
    op.drop_column('item', 'XL_stock')
    op.drop_column('item', 'L_stock')
    op.drop_column('item', 'M_stock')
    # ### end Alembic commands ###
