"""delete colors field in Item model

Revision ID: 909face892ad
Revises: 2390ecb8aae3
Create Date: 2022-05-20 19:27:00.415871

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '909face892ad'
down_revision = '2390ecb8aae3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'colors')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('colors', sqlite.JSON(), nullable=True))
    # ### end Alembic commands ###
