"""add is_deleted field to Item

Revision ID: 927994372bb6
Revises: 639ff25f67e9
Create Date: 2022-05-24 23:04:15.819962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '927994372bb6'
down_revision = '639ff25f67e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'is_deleted')
    # ### end Alembic commands ###
