"""add some fields to Admin models

Revision ID: a50144c4ee92
Revises: 4627732acd9d
Create Date: 2022-05-11 00:44:10.629968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a50144c4ee92'
down_revision = '4627732acd9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('staffname', sa.String(length=64), nullable=True))
    op.add_column('admin', sa.Column('avatar', sa.String(length=140), nullable=True))
    op.add_column('admin', sa.Column('is_manager', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'is_manager')
    op.drop_column('admin', 'avatar')
    op.drop_column('admin', 'staffname')
    # ### end Alembic commands ###
