"""delete response field in contact_form

Revision ID: b4598defefe3
Revises: 54704d21a3ce
Create Date: 2022-05-23 01:23:02.388672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4598defefe3'
down_revision = '54704d21a3ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact_form', 'response')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_form', sa.Column('response', sa.VARCHAR(length=140), nullable=True))
    # ### end Alembic commands ###
