"""delete favourite_list from Customer

Revision ID: b5eb5304dbc1
Revises: 4a4b1115dd46
Create Date: 2022-05-10 23:38:50.881363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5eb5304dbc1'
down_revision = '4a4b1115dd46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'favorite_list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('favorite_list', sa.VARCHAR(length=200), nullable=True))
    # ### end Alembic commands ###
