"""add phone, postal_code, address, and unit_no fields to Customer model

Revision ID: e6121ada4452
Revises: be1f139a92b7
Create Date: 2022-05-23 14:25:16.630345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6121ada4452'
down_revision = 'be1f139a92b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('phone', sa.Integer(), nullable=True))
    op.add_column('customer', sa.Column('postal_code', sa.Integer(), nullable=True))
    op.add_column('customer', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('customer', sa.Column('unit_no', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'unit_no')
    op.drop_column('customer', 'address')
    op.drop_column('customer', 'postal_code')
    op.drop_column('customer', 'phone')
    # ### end Alembic commands ###
